# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2d738da31c61278dd3b123341d958878bf9bc8db872eb82acb00836addb046fd58935c53e04f1997a1298ff169ece5b4364beb9f0427d28070a4cafd293be8b

test:
  secret_key_base: d07a5d396a22d85a676871f545997e355973faa2214371eaf807ceb4a4203a8172d429c87ab28ab32eae3a05e2e064a4509156c61d6f6947e861e4ecd79391fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
